### ISSUE TITLE
Report missing non-null constraints

### ISSUE THREAD

**Issue by tcopeland** [trptcolin/consistency_fail#40]
Any interest in expanding this to report cases where the model has a `presence` validation but the database doesn't have a non-null constraint?

**Comment by trptcolin** [comment]
Interesting idea. The existing cases are really about concurrency-related issues, and this would open the door to a much broader range of possibilities. If I'm understanding correctly, the use case here is that if there's no `NOT NULL` constraint, writes going through ActiveRecord would already do the right thing, but writing to the database directly wouldn't have that same constraint. Have I got that right, or is there a completely AR-based use case? 

If I'm understanding right, I think this would open the door to putting every other AR validation in here too (even down to the level of format, etc.), which is more that I would personally recommend to folks for projects. I do like using the `NOT NULL` constraint, so I'm torn, but my knee-jerk inclination is that this project should focus on reviewing errors that will bite folks in purely-AR scenarios.

However, I'd *love* to allow pluggability of new introspectors, so that people who disagree can add their own or use other folks'. 

I'd love a patch for that kind of thing - I haven't made the time for this project lately, but I would personally place a higher priority on upgrading beyond 3.x if I get any time.

**Comment by tcopeland** [comment]
Yup exactly - this would catch the case where the Active Record model requires the presence of a value but the database does not.  And I agree, there's a slippery slope here where the tool demands that a check constraint be placed on columns if that's on the model, and I also agree that that feels like a bridge too far.

Maybe I can spike something out and run it on my projects and see if the things it finds are actually useful.  Sometimes these ideas seem useful in theory but in practice are only annoying.  I'll let you know!

**Comment by tcopeland** [comment]
Per our discussion https://github.com/tcopeland/nullalign, food for thought!

**Comment by tcopeland** [comment]
Thinking out loud.... googling around for "active record lint" finds https://github.com/tomlea/active_record_lint, which identifies non-indexed foreign keys.  If we implemented that we'd have:

* uniqueness validators without a backing unique constraint
* presence validators without a backing non-null constraint
* foreign keys without an index

I'm trying to think of any others that would make such a project worth pulling together...

**Comment by trptcolin** [comment]
Cool! I'm not aware of others, but wouldn't be surprised to hear that more exist. I'm probably not going to be a good person to create a top-level project like that (the lack of updates to this based on Rails 4-5 are testament to that), but happy to take PRs that make consistency_fail work better with any higher-level thing too.

Thinking through the instrospector-pluggability idea I tossed out earlier, I guess it's trickier than I originally imagined, since consistency_fail is both an executable and a library. I don't have an immediate / obviously-good idea in mind. 

But I'm definitely going to try both nullalign and active_record_lint on the next Rails app I touch! 😄 

Going to close this as an issue, but happy to continue discussing.

**Comment by tommotorefi** [comment]
Cool sounds good @trptcolin !  I'll let you know if I get anywhere on a larger ar-lint effort.
