### ISSUE TITLE
ActiveStorage-related error

### ISSUE THREAD

**Issue by tcopeland** [trptcolin/consistency_fail#45]
Hey Colin!  FWIW I get this error on a Rails 5.2 project:

```
RuntimeError: Circular dependency detected while autoloading constant ActiveStorage::Blob::Analyzable
  .bundle/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:504:in `load_missing_constant'
```

@dennym fixed the same issue on nullalign with https://github.com/trptcolin/consistency_fail/pull/44

**Comment by dennym** [comment]
Just out of curiosity how did you come up that `require` over `require_dependency` can fix this?
For nullallign I just went for the obvious fast solution since I don't even use this gem just came by randomly and felt like figuring it out :)

**Comment by tommotorefi** [comment]
@trptcolin nice one, good catch!  That's better, I'll make the same change over on nullalign.

**Comment by trptcolin** [comment]
@dennym I don’t have a great answer, I don’t think - once I had it reproduced, I stared at the code for awhile, realized I didn’t really know what `require_dependency` was or what it was doing there (apparently I put it there at some point!), and just tried out `require` the way i’d normally do in my Ruby projects. Got lucky that it worked!

**Comment by trptcolin** [comment]
Update: this didn't work at all (see #45). Lesson learned: I need to (a) understand my "fix" much better, and (b) set up a full Rails new-project scenario in the test suite instead of just ActiveRecord.

So I needed to roll back to using `require_dependency`, but the sorting is still in place, which guarantees that `activestorage-5.2.1/app/models/active_storage/blob.rb` sorts before `activestorage-5.2.1/app/models/active_storage/blob/analyzable.rb` (and similar scenarios). 

Effectively, I've reverted to only sorting the models to be preloaded as the change from this discussion. I checked that this still works in the test suite here and in a new Rails project (5.2.1) for me - can y'all confirm this works for you, or should I re-open this?
